import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/session";
import { resolveActivePortfolio } from "@/lib/context";
import { db } from "@/lib/db";
import { PortfolioHeader } from "@/components/shell/PortfolioHeader";
import { Card } from "@/components/ui/Card";
import { Disclaimer } from "@/components/ui/Disclaimer";
import { formatDate } from "@/lib/format";

const SUGGESTIONS = [
  "Why did my portfolio change today?",
  "Which sectors exceed 20% of my portfolio?",
  "What dividends did I receive this financial year?",
  "What changed since last month?",
  "Explain XIRR",
  "Explain allocation drift",
  "What data is missing or stale?",
];

export default async function AiExplainerPage({ searchParams }: { searchParams: { portfolio?: string } }) {
  const user = await getCurrentUser();
  if (!user) redirect("/signin");
  const { portfolios, active } = await resolveActivePortfolio(user, searchParams.portfolio);
  if (!active) redirect("/connections");

  const history = await db.aiQuery.findMany({ where: { userId: user.id }, orderBy: { createdAt: "desc" }, take: 10 });

  return (
    <div className="max-w-2xl space-y-6">
      <PortfolioHeader title="Ask Pulse" subtitle="Grounded answers about your own data — not investment advice" portfolios={portfolios} activeId={active.id} />

      <Card>
        <form action="/api/ai/ask" method="post" className="space-y-2">
          <input type="hidden" name="portfolioId" value={active.id} />
          <textarea name="question" required rows={2} placeholder="Ask about your portfolio…" className="w-full rounded-lg border border-pulse-border bg-pulse-surfaceAlt px-3 py-2 text-sm" />
          <div className="flex flex-wrap gap-1">
            {SUGGESTIONS.map((s) => (
              <span key={s} className="rounded-full border border-pulse-border px-2 py-1 text-[11px] text-pulse-muted">{s}</span>
            ))}
          </div>
          <button type="submit" className="rounded-lg bg-pulse-accent px-4 py-2 text-sm font-medium text-white hover:opacity-90">Ask</button>
        </form>
      </Card>

      <div className="space-y-3">
        {history.map((q) => (
          <Card key={q.id}>
            <p className="text-sm font-medium text-pulse-text">Q: {q.question}</p>
            <p className="mt-1 text-sm text-pulse-muted">{q.answer}</p>
            <p className="mt-2 text-xs text-pulse-muted/70">{formatDate(q.createdAt, { year: "numeric", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })} · intent: {q.intent}</p>
          </Card>
        ))}
      </div>

      <Disclaimer text="Pulse AI answers are generated by rule-based logic grounded only in your own recorded data — not a general-purpose language model, and never a recommendation to buy, sell, or hold. See QUESTIONS.md #10." />
    </div>
  );
}
