import { requireUser } from "@/lib/session";
import { db } from "@/lib/db";
import { computeDriftReport } from "@/lib/risk";
import { toCsv } from "@/lib/csv";
import { writeAuditLog } from "@/lib/audit";

export async function GET(req: Request) {
  const user = await requireUser();
  const url = new URL(req.url);
  const portfolioId = url.searchParams.get("portfolio") || "";
  const contribution = Number(url.searchParams.get("contribution") || "0");

  const portfolio = await db.portfolio.findFirst({ where: { id: portfolioId, userId: user.id } });
  if (!portfolio) return new Response("Not found", { status: 404 });

  const drift = await computeDriftReport(portfolioId);
  const rows = drift.map((d) => [
    d.category,
    (d.actualWeight * 100).toFixed(2),
    (d.targetWeight * 100).toFixed(2),
    (d.drift * 100).toFixed(2),
    d.breachesThreshold ? "REVIEW" : "OK",
  ]);
  const csv = toCsv(["category", "actual_weight_pct", "target_weight_pct", "drift_pct", "status"], rows);
  const note = `\n\n# Contribution modeled: ${contribution}\n# Generated by Pulse. Informational only — not an order or a recommendation. Pulse never places trades.`;

  await writeAuditLog(user.id, "export", { event: "rebalance_checklist_csv", portfolioId });

  return new Response(csv + note, {
    headers: { "Content-Type": "text/csv", "Content-Disposition": `attachment; filename="rebalance-checklist.csv"` },
  });
}
