import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import ExcelJS from "exceljs";

export interface ReportSection {
  heading: string;
  lines: string[];
}

/** Renders a simple print-quality PDF report (PRD "Reports and Exports"). */
export async function renderPdfReport(title: string, subtitle: string, sections: ReportSection[]): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const boldFont = await doc.embedFont(StandardFonts.HelveticaBold);
  const pageWidth = 595;
  const pageHeight = 842;
  const margin = 50;
  let page = doc.addPage([pageWidth, pageHeight]);
  let y = pageHeight - margin;

  const drawText = (text: string, size: number, bold = false, color = rgb(0.1, 0.1, 0.1)) => {
    if (y < margin + 20) {
      page = doc.addPage([pageWidth, pageHeight]);
      y = pageHeight - margin;
    }
    page.drawText(text, { x: margin, y, size, font: bold ? boldFont : font, color, maxWidth: pageWidth - margin * 2 });
    y -= size + 8;
  };

  drawText(title, 20, true);
  drawText(subtitle, 10, false, rgb(0.4, 0.4, 0.4));
  y -= 10;
  drawText(`Generated ${new Date().toISOString()}`, 8, false, rgb(0.5, 0.5, 0.5));
  y -= 10;

  for (const section of sections) {
    y -= 6;
    drawText(section.heading, 13, true);
    for (const line of section.lines) {
      drawText(line, 10);
    }
  }

  y -= 16;
  drawText(
    "This report is generated by Pulse, a portfolio tracking and educational-analytics tool. It is not personalised investment advice and does not guarantee future performance.",
    8,
    false,
    rgb(0.5, 0.5, 0.5),
  );

  const bytes = await doc.save();
  return Buffer.from(bytes);
}

export interface XlsxSheet {
  name: string;
  headers: string[];
  rows: Array<Array<string | number>>;
}

export async function renderXlsxWorkbook(sheets: XlsxSheet[]): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Pulse: Your Portfolio Intelligence";
  workbook.created = new Date();

  for (const sheet of sheets) {
    const ws = workbook.addWorksheet(sheet.name.slice(0, 31));
    ws.addRow(sheet.headers).font = { bold: true };
    for (const row of sheet.rows) ws.addRow(row);
    ws.columns.forEach((col) => {
      col.width = 18;
    });
  }

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
